# -*- coding: utf-8 -*-


[[spot]]
url = "wss://stream.binance.com:9443/ws"

[[margin]]
url = "wss://stream.binance.com:9443/ws"

[[future]]
url = "wss://fstream.binance.com/ws"

[[delivery]]
url = "wss://dstream.binance.com/ws"

[[ws-api-spot]]
url = "wss://ws-api.binance.com:443/ws-api/v3"

[[ws-api-future]]
url = "wss://ws-fapi.binance.com/ws-fapi/v1"

[[papi]]
url = "wss://fstream.binance.com/pm/ws"



