#!/usr/bin/python3
# -*- coding: utf-8 -*-
import json
import redis

CHANNEL_NAME = "notification"
r = redis.Redis()


def send_notification(
    user_id: int, 
    message: str):
    """
    Send a notification to a user.
    note: this maybe located in services.py
    """
    ...
    
    r.publish(CHANNEL_NAME, json.dumps({"user_id": user_id, "message": message}))


def main(queue_redis):
    message = queue_redis.get_nowait()
    # imagine this in view / API endpoint or signals
    send_notification(42, queue_redis)


if __name__ == "__main__":
    main()