#!/usr/bin/python3
# -*- coding: utf-8 -*-
import asyncio
import async_timeout
from loguru import logger as log
import logging
import redis.asyncio as redis
import orjson
from time import sleep


logging.basicConfig(level=logging.DEBUG)

async def handle_notification(CHANNEL_NAME):
    r = redis.Redis()
    pubsub = r.pubsub()     
    await pubsub.subscribe(CHANNEL_NAME)
    while True:
        try:
            async with async_timeout.timeout(1):
                message = await pubsub.get_message()
                log.critical (message)
                if message and message["type"] == "message":
                    payload = orjson.loads(message["data"])
                    # TODO: do validation on payload
                    log.warning (f"{CHANNEL_NAME}, {payload["user_id"]}, {payload["message"]}")
                    await asyncio.sleep(.00001) 
        except Exception as e:
            logging.error(e)


if __name__ == "__main__":
    CHANNEL_NAME = "notification"
    asyncio.run(handle_notification(CHANNEL_NAME))