#!/usr/bin/python3
# -*- coding: utf-8 -*-


import requests
import time
import json
import pandas as pd

import asyncio
import httpx

# https://stackoverflow.com/questions/66686458/how-to-scrape-an-updating-html-table-using-selenium
headers = ['Coin','Pings','Net Vol BTC','Net Vol %','Recent Total Vol BTC', 'Recent Vol %', 'Recent Net Vol', 'Datetime (UTC)']

starttime = time.time()

    
async def main():
    while True:
        response = httpx.get('https://agile-cliffs-23967.herokuapp.com/ok', headers={'Connection': 'keep-alive'})
        d = json.loads(response.text)
        print (f"d1 {d}")
        rows = [str(i).split('|') for i in d['resu'][:-1]]
        print (f"rows {rows}")
        lst = []
        
        async with httpx.AsyncClient() as client:
            
            response = await client.get('https://agile-cliffs-23967.herokuapp.com/ok')
            print (f"response1 {response}")
            d = json.loads(response.text)
            print (f"d2 {d}")

        async with httpx.AsyncClient(headers={'Connection': 'keep-alive'}) as client:
            
            response = await client.get('https://agile-cliffs-23967.herokuapp.com/ok')
            print (f"response2 {response}")

        if rows:
            data = [dict(zip(headers, l)) for l in rows]
            print (f"data {data}")

            for row in rows:
                lst.append(row)
                print (f"row {row}")
            print (f"lst {lst}")
        time.sleep(60.0 - ((time.time() - starttime) % 60.0))

asyncio.run (main())