#!/usr/bin/python3
# -*- coding: utf-8 -*-


import requests
import time
import json
import pandas as pd
# https://stackoverflow.com/questions/66686458/how-to-scrape-an-updating-html-table-using-selenium
headers = ['Coin','Pings','Net Vol BTC','Net Vol %','Recent Total Vol BTC', 'Recent Vol %', 'Recent Net Vol', 'Datetime (UTC)']

s = requests.Session()
starttime = time.time()

    
import asyncio
import httpx


async def main():
    cat_url = 'https://agile-cliffs-23967.herokuapp.com/ok'

    async with httpx.AsyncClient(headers={'Connection': 'keep-alive'}) as client:

        resp = await client.get(cat_url)

        cat = resp.json()
        print(cat['url'])

asyncio.run(main())


while True:
    response = s.get('https://agile-cliffs-23967.herokuapp.com/ok', headers={'Connection': 'keep-alive'})
    d = json.loads(response.text)
    rows = [str(i).split('|') for i in d['resu'][:-1]]
    print (f"rows {rows}")
    lst = []
    if rows:
        data = [dict(zip(headers, l)) for l in rows]
        print (data)

        for row in rows:
            lst.append(row)
            print (f"row {row}")
        print (f"lst {lst}")
    time.sleep(60.0 - ((time.time() - starttime) % 60.0))
