#!/usr/bin/python3
# -*- coding: utf-8 -*-
import asyncio
import async_timeout
import json
import logging
import redis.asyncio as redis
import orjson
import aioredis

CHANNEL_NAME = "notification"

            
async def subscribe(channel):
    redis = await aioredis.from_url("redis://localhost")
    
    channel = await redis.subscribe(channel)
    async for message in channel[0].iter():
        # process message
        print(message)

#asyncio.run(subscribe("my-channel")) 

if __name__ == "__main__":
    asyncio.run(subscribe("notification"))