#!/usr/bin/python3
# -*- coding: utf-8 -*-


import requests
import time
import json
import pandas as pd
from loguru import logger as log
import asyncio
import httpx

# https://stackoverflow.com/questions/66686458/how-to-scrape-an-updating-html-table-using-selenium
headers = ['Coin','Pings','Net Vol BTC','Net Vol %','Recent Total Vol BTC', 'Recent Vol %', 'Recent Net Vol', 'Datetime (UTC)']

starttime = time.time()

    
async def main():
    while True:
        async with httpx.AsyncClient(headers={'Connection': 'keep-alive'}) as client:
            
            response = await client.get('https://agile-cliffs-23967.herokuapp.com/ok')
            log.info (f"response1 {response}")
            d = json.loads(response.text)
            log.warning (f"d2 {d}")
            
            rows = [str(i).split('|') for i in d['resu'][:-1]]
            log.info (f"rows {rows}")
            
            data = [dict(zip(headers, l)) for l in d]
            log.debug (f"data5 {data}")


        time.sleep(60.0 - ((time.time() - starttime) % 60.0))

asyncio.run (main())