#!/usr/bin/python3
# -*- coding: utf-8 -*-

# built ins
import asyncio
from datetime import datetime, timedelta, timezone
import os

# installed
from dataclassy import dataclass, fields
import json
from loguru import logger as log
import orjson
import tomli
import websockets
import asyncio
import websockets
import json

import time
import hashlib
import hmac
from urllib.parse import urlencode

from transaction_management.deribit.managing_deribit import (
    ModifyOrderDb)

# user defined formula
from configuration import id_numbering, config#, config_oci

from utilities.system_tools import (
    provide_path_for_file,
    async_raise_error_message,
    raise_error_message,)


from utilities.string_modification import (
    hashing,)


def parse_dotenv (sub_account) -> dict:
    return config.main_dotenv(sub_account)

def get_config(file_name: str) -> list:
    """ """
    config_path = provide_path_for_file (file_name)
    
    try:
        if os.path.exists(config_path):
            with open(config_path, "rb") as handle:
                read= tomli.load(handle)
                return read
    except:
        return []

def hashing(
    query_string,
    apiSecret
    )-> str:
    
    
    return hmac.new(
        apiSecret.encode("utf-8"), 
        query_string.encode("utf-8"), 
        hashlib.sha256
        ).hexdigest()


def get_timestamp():
    return int(time.time() * 1000)

""" === end of util functions === """
 
 
@dataclass(unsafe_hash=True, slots=True)
class StreamAccountData(ModifyOrderDb):

    sub_account_id: str
    client_id: str = fields 
    client_secret: str = fields 
    modify_order_and_db: object = fields 
    # Async Event Loop
    loop = asyncio.get_event_loop()
    
    websocket_client: websockets.WebSocketClientProtocol = None
    refresh_token: str = None
    refresh_token_expiry_time: int = None
            
    def __post_init__(self):
        self.modify_order_and_db: str = ModifyOrderDb(self.sub_account_id)
        self.client_id: str = parse_dotenv(self.sub_account_id)["my_id"]
        self.client_secret: str = (parse_dotenv(self.sub_account_id)["my_secret"])
        
        # Start Primary Coroutine
        self.loop.run_until_complete(self.ws_manager())
    
    async def ws_manager(self) -> None:
        
        # parsing config file
        file_toml = "api_url_end_point.toml"
        
        config_app_url = get_config(file_toml)
        
        connection_kind = config_app_url["ws-api-spot"]
        
        url =  (connection_kind["url"])
        
        timestamp = get_timestamp()
        
        payload = {
            "apiKey": self.client_id,
            "timestamp": timestamp
        }
        
        encoding_result = hashing(
            urlencode(payload),
            self.client_secret
            )
        
        async with websockets.connect(
            url,
            ping_interval=None,
            compression=None,
            close_timeout=60,
            ) as self.websocket_client:
            while True:
                     
                while self.websocket_client.open:
                    
                    account_balance = connection_kind["account_status"]
                    #ticker_price = connection_kind["ticker_price"]
                    
                    await self.ws_auth(
                        True,
                        account_balance,
                        encoding_result,
                        timestamp
                        )
                    
                    # Receive WebSocket messages
                    message: bytes = await self.websocket_client.recv()
                    message: dict = orjson.loads(message)

                    log.warning (message)


    async def ws_auth(
        self,
        is_authenticated: bool,
        method: str,
        signature: str,
        timestamp: int,
        params: str = None) -> None:
        
        """
        Requests DBT's `public/auth` to
        authenticate the WebSocket Connection.
        """
        sleep_time: int = .5
        
        await asyncio.sleep(sleep_time)

        msg: dict = {
            "id": "605a6d20-6588-4cb9-afa0-b0ab7507ba",
            "method": method}
        
        log.error (f"is_authenticated {is_authenticated}")
        log.error (f"basic_msg {msg}")
        log.error (f"method {method}")
        
        if is_authenticated:
            msg_authenticated =    {
                "apiKey": self.client_id,
                "timestamp": timestamp,
                "signature": signature
            }     
            
            msg.update({"params": msg_authenticated})
        
        else:
            if  params:
                msg.update({"params": params})
        
        log.error (f"params {params}")
        log.error (f"params {msg_authenticated}")
            
        try:
            log.error (f"msg {msg}")
            await self.websocket_client.send(json.dumps(msg))

        except Exception as error:
            
            raise_error_message (
            error, 
            1,
            "app"
            )


def main():

    sub_account_id = "binance-sub-1"
    
    try:
        StreamAccountData(sub_account_id)

    except Exception as error:
        log.critical (error)
        raise_error_message (
            error, 
            3,
            "app"
            )

                
if __name__ == "__main__":
    
    try:
        main()
        
    except(
        KeyboardInterrupt, 
        SystemExit
        ):
        asyncio.get_event_loop().run_until_complete(main().stop_ws())
        
    except Exception as error:
        log.critical (error)
        asyncio. telegram_bot_sendtext (
            error,
            "general_error"
            )
        raise_error_message(
        error, 
        3, 
        "app"
        )
