#!/usr/bin/python3
# -*- coding: utf-8 -*-

# built ins
import asyncio
from asyncio import Queue
import signal
import sys

# installed
import uvloop
import redis.asyncio as aioredis
#from redistimeseries.client import Client

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

from data_cleaning.pruning_db import clean_up_databases
from messaging.telegram_bot import telegram_bot_sendtext
from streaming_data.data_producer import StreamingAccountData
from transaction_management.deribit.api_requests import (
    get_currencies,
    get_instruments,
    SendApiRequest,
)
from transaction_management.deribit.get_instrument_summary import (
    get_futures_instruments,
)
from utilities.system_tools import (
    SignalHandler,
    back_up_db,
    get_config_tomli,
    parse_error_message, 
    provide_path_for_file,
    )
from utilities.string_modification import (
    remove_double_brackets_in_list,
    remove_redundant_elements,
)
from utilities.pickling import replace_data


def handle_ctrl_c(
    signum, 
    stack_frame
    )->None:
    
    sys.exit(0)
    
                  
signal_handler = SignalHandler()

async def main():
    """
    https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html
    """
    sub_account_id = "deribit-148510"

    # registering strategy config file    
    file_toml = "config_strategies.toml"
    
    try:

        private_data: object = SendApiRequest(sub_account_id)

        pool = aioredis.ConnectionPool.from_url(
            "redis://localhost", 
            port=6379, 
            db=0, 
            protocol=3, 
            encoding="utf-8",
            decode_responses=True
            )
        
        client_redis: object = aioredis.Redis.from_pool(pool)
        
        # parsing config file
        config_app = get_config_tomli(file_toml)

        # get tradable strategies
        tradable_config_app = config_app["tradable"]

        # get ALL traded currencies in deribit
        get_currencies_all = await get_currencies()

        all_exc_currencies = [
            o["currency"] for o in get_currencies_all["result"]
        ]

        for currency in all_exc_currencies:

            instruments = await get_instruments(currency)

            my_path_instruments = provide_path_for_file("instruments", currency)

            replace_data(
                my_path_instruments,
                instruments,
            )

        my_path_cur = provide_path_for_file("currencies")

        replace_data(
            my_path_cur,
            all_exc_currencies,
        )

        # get TRADABLE currencies
        currencies: list = [o["spot"] for o in tradable_config_app][0]

        strategy_attributes = config_app["strategies"]

        settlement_periods = remove_redundant_elements(
        remove_double_brackets_in_list(
            [o["settlement_period"] for o in strategy_attributes]
        )
    )
        
        futures_instruments = await get_futures_instruments(
            currencies,
            settlement_periods,
        )

        # get redis channels
        redis_channels: dict = config_app["redis_channels"][0]

        resolutions: list = [o["resolutions"] for o in tradable_config_app][0]

        strategy_attributes = config_app["strategies"]

        queue = Queue(maxsize=1)
        
        stream = StreamingAccountData(sub_account_id)
                
        producer_task = asyncio.create_task(
            stream.ws_manager(
                client_redis,
                redis_channels,
                queue,
                futures_instruments,
                resolutions,
)
            ) 
                        
        await asyncio.sleep(0.0005)
                    
        await asyncio.gather(
            producer_task, 
        
            back_up_db(60*10),
            
            clean_up_databases(60)
            
                        )  

        await queue.join()

    except Exception as error:
        
        parse_error_message(error)
        await telegram_bot_sendtext (
            f"app-{error}",
            "general_error"
            )

if __name__ == "__main__":
    
    try:
        signal.signal(signal.SIGINT, handle_ctrl_c) # terminate on ctrl-c
        
        uvloop.run(main())
        
    except(
        KeyboardInterrupt, 
        SystemExit
        ):
        
        asyncio.get_event_loop().run_until_complete(main())
        
    except Exception as error:
        parse_error_message(error)
        
        asyncio.run(telegram_bot_sendtext (
            error,
            "general_error"
            ))
