#!/usr/bin/python
# -*- coding: utf-8 -*-

# built ins
import asyncio

# installed
from loguru import logger as log

# user defined formula
from db_management.sqlite_management import (
    update_status_data,)
from utilities.system_tools import (
    async_raise_error_message,)

async def updating_db_with_new_label(
    trade_db_table: str,
    archive_db_table: str,
    trade_id: str,
    filter: str,
    new_label: str 
    ) -> None:
    """
    
    
    """
                
    try:
        await update_status_data(
        archive_db_table,
        "label",
        filter,
        trade_id,
        new_label,
        "="
        )
    
        await update_status_data(
        trade_db_table,
        "label",
        filter,
        trade_id,
        new_label,
        "="
        )
    
    
    except Exception as error:
        await async_raise_error_message(error)
        
            
        
if __name__ == '__main__':

    trade_db_table= "my_trades_all_json"
    
    order_db_table= "orders_all_json"
    
    currency_lower = "btc"
    
    archive_db_table = f"my_trades_all_{currency_lower}_json"      
    
    filter = "trade_id"
    
    trade_id = "330882029"
    
    new_label = "futureSpread-open-1733120308427"
                  
    asyncio.run(updating_db_with_new_label(
    trade_db_table,
    archive_db_table,
    trade_id,
    filter,
    new_label 
    ))