#!/usr/bin/python3
# -*- coding: utf-8 -*-

# built ins
import asyncio
import pandas as pd
from utilities.string_modification import extract_integers_from_text
from db_management.sqlite_management import (
    executing_query_based_on_currency_or_instrument_and_strategy as get_query)


async def get_db_trade():
                
    column_trade: str= "instrument_name","label", "amount", "price","trade_id"
    my_trades_currency: list= await get_query("my_trades_all_json", 
                                                "BTC", 
                                                "all", 
                                                "all", 
                                                column_trade)
    
    return [{key: value for key, value in dict.items() if key != 'balance'} for dict in my_trades_currency]

async def get_open_orders():
                
    column_trade: str= "instrument_name","label", "amount", "price"
    orders_currency: list= await get_query("orders_all_json", 
                                                "BTC", 
                                                "all", 
                                                "all", 
                                                column_trade)
    
    
    return [{key: value for key, value in dict.items() if key != 'balance'} for dict in orders_currency]

async def main():
    #data = await fetch_data('https://www.deribit.com/api/v2/public/ticker?instrument_name=BTC-PERPETUAL')
    #st.dataframe(data["result"])
    pd.set_option("display.float_format", "${:,.2f}".format)

    try:
                
        data_trading = await get_db_trade ()
        
        data_orders = await get_open_orders ()
        
        data_trading_custom = [o for o in data_trading\
            if "custom" in o["label"]]
       
        
        df = pd.DataFrame(data_trading_custom)
        
        df.drop(columns=["amount"])

        df['integer'] = df['label'].str.extract('(\d+)')
        df['premium'] = ((df['price']*abs(df["amount"]))/df["amount"])
        
        df = pd.pivot_table(
            df,
            values="premium",
            index=["integer","trade_id","label","instrument_name","amount"],
            aggfunc="sum", 
            )
        print (df.to_string())
        
        
        data_orders_custom = [o for o in data_orders\
            if "custom" in o["label"]]
        
        if data_orders_custom:
            df = pd.DataFrame(data_orders_custom)
            
            df['integer'] = df['label'].str.extract('(\d+)')
            
            df = pd.pivot_table(
                df,
                index=["integer","label","instrument_name","amount"],
                aggfunc="sum", 
                )
            print (df.to_string())
        
    except Exception as error:
        await print(error)
        
        
if __name__ == '__main__':


    asyncio.run(main())